#%RAML 1.0
title: Echo API
mediaType:
  - application/json
version: v1
/echo:
  get:
    displayName: Echo Client
    responses:
      "200":
        body:
          example: Example
          type: string
/ping:
  get:
    displayName: Test Endpoint
    responses:
      "200":
        body:
          example: Pong
          type: string
securedBy: []
